In [1]:
import pandas as pd
from pathlib import Path

In [2]:
raw_data_path= Path("../data/raw")
datasets={}
csv_files = list(raw_data_path.glob("*.csv"))
print(f"Found {len(csv_files)} CSV files")
for file in csv_files:
    try:
        df=pd.read_csv(file)
        dataset_name=file.stem
        datasets[dataset_name]=df
        print(f"loaded: {dataset_name}")
    except Exception as e:
        print(f"Error loading {file.name}:{e}")

Found 10 CSV files
loaded: 01_fund_master
loaded: 02_nav_history
loaded: 03_aum_by_fund_house
loaded: 04_monthly_sip_inflows
loaded: 05_category_inflows
loaded: 06_industry_folio_count
loaded: 07_scheme_performance
loaded: 08_investor_transactions
loaded: 09_portfolio_holdings
loaded: 10_benchmark_indices

In [3]:
for name, df in datasets.items():

    print("=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    display(df.head())

================================================================================
DATASET: 01_fund_master
================================================================================

Shape:
(40, 15)

Column Names:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

Data Types:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

First 5 Rows:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

================================================================================
DATASET: 02_nav_history
================================================================================

Shape:
(46000, 3)

Column Names:
['amfi_code', 'date', 'nav']

Data Types:
amfi_code      int64
date          object
nav          float64
dtype: object

First 5 Rows:

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

================================================================================
DATASET: 03_aum_by_fund_house
================================================================================

Shape:
(90, 5)

Column Names:
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

Data Types:
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

First 5 Rows:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

================================================================================
DATASET: 04_monthly_sip_inflows
================================================================================

Shape:
(48, 6)

Column Names:
['month', 'sip_inflow_crore', 'active_sip_accounts_crore', 'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct']

Data Types:
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

First 5 Rows:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

================================================================================
DATASET: 05_category_inflows
================================================================================

Shape:
(144, 3)

Column Names:
['month', 'category', 'net_inflow_crore']

Data Types:
month                object
category             object
net_inflow_crore    float64
dtype: object

First 5 Rows:

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

================================================================================
DATASET: 06_industry_folio_count
================================================================================

Shape:
(21, 6)

Column Names:
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

Data Types:
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

First 5 Rows:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

================================================================================
DATASET: 07_scheme_performance
================================================================================

Shape:
(40, 19)

Column Names:
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

Data Types:
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

First 5 Rows:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

================================================================================
DATASET: 08_investor_transactions
================================================================================

Shape:
(32778, 13)

Column Names:
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

Data Types:
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

First 5 Rows:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

================================================================================
DATASET: 09_portfolio_holdings
================================================================================

Shape:
(322, 8)

Column Names:
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

Data Types:
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

First 5 Rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

================================================================================
DATASET: 10_benchmark_indices
================================================================================

Shape:
(8050, 3)

Column Names:
['date', 'index_name', 'close_value']

Data Types:
date            object
index_name      object
close_value    float64
dtype: object

First 5 Rows:

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [ ]:
#missing values
for name, df in datasets.items():

    print(f"\n{name}")
    print(df.isnull().sum())

01_fund_master
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

02_nav_history
amfi_code    0
date         0
nav          0
dtype: int64

03_aum_by_fund_house
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

04_monthly_sip_inflows
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

05_category_inflows
month               0
category            0
net_inflow_crore    0
dtype: int64

06_industry_folio_count
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

07_scheme_performance
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

08_investor_transactions
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

09_portfolio_holdings
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

10_benchmark_indices
date           0
index_name     0
close_value    0
dtype: int64

In [5]:
#duplicate rows
for name, df in datasets.items():

    print(f"{name}: {df.duplicated().sum()} duplicate rows")

01_fund_master: 0 duplicate rows
02_nav_history: 0 duplicate rows
03_aum_by_fund_house: 0 duplicate rows
04_monthly_sip_inflows: 0 duplicate rows
05_category_inflows: 0 duplicate rows
06_industry_folio_count: 0 duplicate rows
07_scheme_performance: 0 duplicate rows
08_investor_transactions: 0 duplicate rows
09_portfolio_holdings: 0 duplicate rows
10_benchmark_indices: 0 duplicate rows

In [6]:
#summary dataset
for name, df in datasets.items():

    print(f"{name}")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print("-" * 40)

01_fund_master
Rows: 40
Columns: 15
----------------------------------------
02_nav_history
Rows: 46000
Columns: 3
----------------------------------------
03_aum_by_fund_house
Rows: 90
Columns: 5
----------------------------------------
04_monthly_sip_inflows
Rows: 48
Columns: 6
----------------------------------------
05_category_inflows
Rows: 144
Columns: 3
----------------------------------------
06_industry_folio_count
Rows: 21
Columns: 6
----------------------------------------
07_scheme_performance
Rows: 40
Columns: 19
----------------------------------------
08_investor_transactions
Rows: 32778
Columns: 13
----------------------------------------
09_portfolio_holdings
Rows: 322
Columns: 8
----------------------------------------
10_benchmark_indices
Rows: 8050
Columns: 3
----------------------------------------

In [7]:
list(datasets.keys())

['01_fund_master',
 '02_nav_history',
 '03_aum_by_fund_house',
 '04_monthly_sip_inflows',
 '05_category_inflows',
 '06_industry_folio_count',
 '07_scheme_performance',
 '08_investor_transactions',
 '09_portfolio_holdings',
 '10_benchmark_indices']

04_monthly_sip_inflows
Missing Values Found:
yoy_growth_pct    12
dtype: int64

In [12]:
#exploring fund_master
fund_master =pd.read_csv("../data/raw/01_fund_master.csv")
print("="*80)
print ("FUND MASTER EXPLORATION")
print("="*80)
# Shape
print("\nShape of Dataset:")
print(fund_master.shape)

# Data Types
print("\nData Types:")
print(fund_master.dtypes)

# First 5 Rows
print("\nFirst 5 Rows:")
print(fund_master.head())

# Missing Values
print("\nMissing Values:")
print(fund_master.isnull().sum())

# Duplicate Rows
print("\nDuplicate Rows:")
print(fund_master.duplicated().sum())

# Column Names
print("\nColumns:")
print(fund_master.columns.tolist())

# Descriptive Statistics
print("\nNumerical Summary:")
print(fund_master.describe())

# Check if Scheme Code is Unique
if 'scheme_code' in fund_master.columns:
    print("\nScheme Code Uniqueness:")
    print(fund_master['scheme_code'].is_unique)

    print("\nDuplicate Scheme Codes:")
    print(fund_master['scheme_code'].duplicated().sum())

# Unique Fund Houses
if 'fund_house' in fund_master.columns:
    print("\nNumber of Fund Houses:")
    print(fund_master['fund_house'].nunique())

    print("\nFund Houses:")
    print(fund_master['fund_house'].unique())

# Categories
if 'category' in fund_master.columns:
    print("\nCategory Distribution:")
    print(fund_master['category'].value_counts())

# Sub Categories
if 'sub_category' in fund_master.columns:
    print("\nSub Category Distribution:")
    print(fund_master['sub_category'].value_counts())

# Risk Grades
if 'risk_grade' in fund_master.columns:
    print("\nRisk Grade Distribution:")
    print(fund_master['risk_grade'].value_counts())

================================================================================
FUND MASTER EXPLORATION
================================================================================

Shape of Dataset:
(40, 15)

Data Types:
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

First 5 Rows:
   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

Missing Values:
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicate Rows:
0

Columns:
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

Numerical Summary:
           amfi_code  expense_ratio_pct  exit_load_pct  min_sip_amount  \
count      40.000000          40.000000      40.000000            40.0
mean   120247.000000           1.237000       0.812500           500.0
std     14534.998667           0.386584       0.387091             0.0
min    100016.000000           0.550000       0.000000           500.0
25%    118632.750000           0.787500       1.000000           500.0
50%    119551.500000           1.425000       1.000000           500.0
75%    120842.250000           1.540000       1.000000           500.0
max    149324.000000           1.640000       1.000000           500.0

       min_lumpsum_amount
count           40.000000
mean          1277.500000
std           1082.847031
min            100.000000
25%           1000.000000
50%           1000.000000
75%           1000.000000
max           5000.000000

Number of Fund Houses:
10

Fund Houses:
['SBI Mutual Fund' 'HDFC Mutual Fund' 'ICICI Prudential MF'
 'Nippon India MF' 'Kotak Mahindra MF' 'Axis Mutual Fund'
 'Aditya Birla Sun Life MF' 'UTI Mutual Fund' 'Mirae Asset MF'
 'DSP Mutual Fund']

Category Distribution:
category
Equity    34
Debt       6
Name: count, dtype: int64

Sub Category Distribution:
sub_category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Short Duration      1
Value               1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

In [17]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

# Get unique AMFI codes
master_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

# Find missing codes
missing_codes = master_codes - nav_codes

print("Total AMFI Codes in fund_master:", len(master_codes))
print("Total AMFI Codes in nav_history:", len(nav_codes))
print("Missing AMFI Codes:", len(missing_codes))

if missing_codes:
    print("\nMissing AMFI Codes:")
    print(sorted(list(missing_codes)))
else:
    print("\n All AMFI codes in fund_master exist in nav_history")

Total AMFI Codes in fund_master: 40
Total AMFI Codes in nav_history: 40
Missing AMFI Codes: 0

 All AMFI codes in fund_master exist in nav_history